/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './about.html',
    './services.html',
    './before-after.html',
    './videos.html',
    './global_header.html',
    './services/**/*.html',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#96f1fa',
        'tertiary-fixed-dim': '#caf0ec',
        'on-primary-fixed-variant': '#00666d',
        'on-background': '#2c3436',
        'on-secondary-container': '#2b5765',
        error: '#a83836',
        'on-surface-variant': '#596063',
        secondary: '#3a6573',
        'accent-gold': '#D4AF37',
        'accent-gold-light': '#E5C76B',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#dce4e6',
        'secondary-dim': '#2d5966',
        'surface-bright': '#f8fafb',
        'on-tertiary-fixed': '#2f514f',
        primary: '#006a71',
        'surface-container': '#eaeff0',
        'inverse-on-surface': '#9a9d9e',
        'on-primary-fixed': '#00474c',
        'outline-variant': '#acb3b6',
        'on-surface': '#2c3436',
        'secondary-fixed': '#bdeafa',
        'inverse-surface': '#0b0f10',
        'inverse-primary': '#99f4fd',
        'secondary-fixed-dim': '#afdbeb',
        'surface-container-low': '#f0f4f6',
        'error-container': '#fa746f',
        outline: '#747c7e',
        'on-secondary': '#f0fbff',
        'on-error': '#fff7f6',
        'primary-fixed': '#96f1fa',
        background: '#f8fafb',
        'on-secondary-fixed-variant': '#36616f',
        'surface-container-high': '#e3e9eb',
        tertiary: '#436563',
        'on-primary': '#e7fdff',
        'surface-dim': '#d4dbde',
        'tertiary-fixed': '#d8fefa',
        'on-tertiary-fixed-variant': '#4c6e6c',
        'error-dim': '#67040d',
        'tertiary-dim': '#375957',
        'tertiary-container': '#d8fefa',
        'primary-fixed-dim': '#88e3eb',
        'secondary-container': '#bdeafa',
        'surface-tint': '#006a71',
        'on-error-container': '#6e0a12',
        'on-primary-container': '#005b61',
        'on-tertiary': '#e1fffc',
        'on-tertiary-container': '#416361',
        'surface-variant': '#dce4e6',
        'on-secondary-fixed': '#164552',
        'primary-dim': '#005d63'
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Manrope'],
        label: ['Manrope'],
        display: 'Manrope'
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px'
      }
    }
  },
  plugins: []
}
